"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var profesional_1 = require("./profesional");
var movie_1 = require("./movie");
var actor1 = new profesional_1.Professional("Actor 1", 30, 70, 180, false, "Country 1", 0, "Actor");
var actor2 = new profesional_1.Professional("Actor 2", 35, 65, 175, false, "Country 2", 1, "Actor");
var movie = new movie_1.Movie("Título de la película", 2023, "Country 3", "Drama");
var director = new profesional_1.Professional("Director", 68, 78, 190, false, "Country 3", 3, "Director");
var writer = new profesional_1.Professional("Escritor", 33, 56, 162, false, "Country 4", 3, "Escritor");
movie.language = "Español";
movie.plataforma = "Online";
movie.isMCU = true;
movie.mainCharacterName = "Name";
movie.producer = "El elefante azul";
movie.distributor = "Leny's";
movie.actors = [actor1, actor2];
movie.director = director;
movie.writer = writer;
movie.printMovie();
